# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=32)),
                ('perm_token', models.CharField(max_length=128)),
                ('last_check', models.DateTimeField()),
                ('contact_type', models.CharField(max_length=16)),
                ('contact_id', models.CharField(max_length=128)),
            ],
        ),
    ]
