# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakalari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=32)),
                ('real_name', models.CharField(max_length=64)),
                ('login_count', models.PositiveSmallIntegerField(default=0)),
                ('dashboard_count', models.PositiveSmallIntegerField(default=0)),
                ('subject_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
