# Generated by Django 2.0.2 on 2018-02-18 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakalari', '0002_logsubject_loguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSubject2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogUser2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('school', models.CharField(max_length=256)),
                ('dashboard_count', models.PositiveSmallIntegerField(default=0)),
                ('subject_count', models.PositiveSmallIntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='LogSubject',
        ),
        migrations.DeleteModel(
            name='LogUser',
        ),
    ]
