# Generated by Django 2.0.2 on 2018-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakalari', '0003_auto_20180218_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='failed_checks',
            field=models.IntegerField(default=0),
        ),
    ]
